/**
 * @krakaw/webhooks - Database Schema
 *
 * Drizzle ORM schema for webhook storage (PostgreSQL).
 * Projects should import and include this table in their schema.
 *
 * @example
 * ```typescript
 * import { webhooks } from '@krakaw/webhooks/schema';
 * export { webhooks };
 * ```
 */

import { pgTable, text, timestamp, boolean, jsonb, integer } from 'drizzle-orm/pg-core';

/**
 * webhooks — outgoing HTTP callbacks registered by users.
 *
 * When an event occurs, the application sends a signed POST request to
 * each matching webhook URL. The payload is signed with HMAC-SHA256
 * using the stored secret; consumers should verify the signature.
 *
 * Signature header: X-{ProjectName}-Signature: sha256=<hex-digest>
 * Payload: JSON body of the event
 *
 * Each webhook can subscribe to one or more event types.
 * An empty events array means "subscribe to all events".
 */
export const webhooks = pgTable('webhooks', {
  /** Primary key — UUID generated by DB */
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),

  /** FK → users.id — the webhook owner */
  userId: text('user_id').notNull(),

  /** Human-readable label for this webhook (e.g. "Slack integration") */
  name: text('name').notNull().default(''),

  /** The URL to POST to */
  url: text('url').notNull(),

  /**
   * HMAC-SHA256 signing secret.
   * Generated on creation; displayed once to the user.
   */
  secret: text('secret').notNull(),

  /**
   * List of event types to subscribe to.
   * e.g. ["booking.created", "transcript.ready"]
   * Empty array = subscribe to all events.
   */
  events: jsonb('events').$type<string[]>().notNull().default([]),

  /** Whether this webhook is active */
  enabled: boolean('enabled').notNull().default(true),

  /** Timestamp of the last successful delivery */
  lastDeliveredAt: timestamp('last_delivered_at', { withTimezone: true }),

  /** HTTP status from the last delivery attempt */
  lastDeliveryStatus: integer('last_delivery_status'),

  /** Timestamp of last failed delivery attempt (null if last attempt succeeded) */
  lastFailedAt: timestamp('last_failed_at', { withTimezone: true }),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Type inference helper for inserts.
 */
export type WebhookInsert = typeof webhooks.$inferInsert;

/**
 * Type inference helper for selects.
 */
export type WebhookSelect = typeof webhooks.$inferSelect;
